# Generated by Django 5.1.3 on 2024-11-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timereading',
            name='sensor_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timereading',
            name='server_time',
            field=models.DateTimeField(),
        ),
    ]
