# Generated by Django 5.1.3 on 2024-11-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timings', '0002_alter_timereading_sensor_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timereading',
            name='server_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
