# Generated by Django 5.1.3 on 2024-11-13 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timings', '0003_alter_timereading_server_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timereading',
            options={'ordering': ['-server_time'], 'verbose_name': 'Time Reading', 'verbose_name_plural': 'Time Readings'},
        ),
    ]
