# Generated by Django 5.1.3 on 2024-11-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timings', '0004_alter_timereading_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timereading',
            name='sensor_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='timereading',
            name='server_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='timereading',
            name='time_mark',
            field=models.CharField(choices=[('START', 'Start'), ('FINISH', 'Finish'), ('COMBINED', 'Combined'), ('FAULTY_READING', 'Faulty Reading')], max_length=100),
        ),
    ]
