# Generated by Django 5.1.3 on 2025-06-29 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_competitionpenalty_options_and_more'),
        ('timings', '0005_alter_timereading_sensor_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=100, unique=True)),
                ('sensor_type', models.CharField(choices=[('START_SENSOR', 'Start Sensor'), ('FINISH_SENSOR', 'Finish Sensor')], max_length=20)),
                ('last_alive_signal', models.DateTimeField()),
                ('is_online', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sensor Status',
                'verbose_name_plural': 'Sensor Statuses',
                'ordering': ['sensor_type', 'sensor_id'],
            },
        ),
        migrations.AddField(
            model_name='timereading',
            name='sensor_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='timereading',
            name='competition_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.competitionstart'),
        ),
        migrations.AlterField(
            model_name='timereading',
            name='time_mark',
            field=models.CharField(choices=[('START', 'Start'), ('FINISH', 'Finish'), ('COMBINED', 'Combined'), ('FAULTY_READING', 'Faulty Reading'), ('ALIVE', 'Alive')], max_length=100),
        ),
    ]
