# Generated by Django 5.1.3 on 2024-11-11 15:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fence',
            name='angle',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fence',
            name='coordinates',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CompetitionStart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starting_order', models.IntegerField()),
                ('has_started', models.BooleanField()),
                ('has_finished', models.BooleanField()),
                ('completion_time', models.TimeField()),
                ('penalty_points', models.IntegerField()),
                ('is_elimination', models.BooleanField()),
                ('elimination_type', models.CharField(choices=[('SECOND_REFUSAL', 'Second Refusal'), ('FALLING_OFF', 'Falling Off'), ('FALSTART', 'Falstart'), ('EXCEEDING_TIME_TWICE', 'Exceeding Time Twice'), ('HAND_OFF_REINS', 'Hand Off Reins'), ('HITTING_GROUND', 'Hitting Ground'), ('CONSTANT_TROTTING', 'Constant Trotting'), ('WRONG_OBSTACLE', 'Wrong Obstacle'), ('DANGEROUS_BEHAVIOUR', 'Dangerous Behaviour'), ('DISREGARDING_JUDGES', 'Disregarding Judges'), ('UNAUTHORIZED_JUMP', 'Unauthorized Jump'), ('LEAVING_ARENA', 'Leaving Arena'), ('FAILURE_TO_ARRIVE', 'Failure To Arrive'), ('OTHER', 'Other')], max_length=100)),
                ('notes', models.TextField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.competition')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.participant')),
            ],
        ),
        migrations.DeleteModel(
            name='CompetitionStartingList',
        ),
    ]
