# Generated by Django 5.1.3 on 2024-11-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_course_options_alter_fence_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fence',
            name='parkour_order',
        ),
        migrations.AddField(
            model_name='fence',
            name='course_order',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='fences',
            field=models.ManyToManyField(related_name='course', to='events.fence'),
        ),
        migrations.AlterField(
            model_name='fence',
            name='angle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fence',
            name='coordinates',
            field=models.CharField(default='0,0', max_length=100),
        ),
        migrations.AlterField(
            model_name='fence',
            name='is_combination',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hobbyhorse',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hobbyhorse',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='judge',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='hobby_horses',
            field=models.ManyToManyField(blank=True, null=True, to='events.hobbyhorse'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
