# Generated by Django 5.1.3 on 2024-11-13 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_fence_parkour_order_fence_course_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='fences',
        ),
        migrations.AddField(
            model_name='fence',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='fences', to='events.course'),
            preserve_default=False,
        ),
    ]
