# Generated by Django 5.1.3 on 2024-11-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_course_description_alter_course_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['-start_date'], 'verbose_name': 'Competition', 'verbose_name_plural': 'Competitions'},
        ),
        migrations.RemoveField(
            model_name='competition',
            name='time',
        ),
        migrations.AddField(
            model_name='competition',
            name='start_date',
            field=models.DateTimeField(default='2024-11-11 11:11'),
            preserve_default=False,
        ),
    ]
