# Generated by Django 5.1.3 on 2024-11-13 12:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_competition_options_remove_competition_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['-start_date_time'], 'verbose_name': 'Competition', 'verbose_name_plural': 'Competitions'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_date'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventstartingnumber',
            options={'ordering': ['number'], 'verbose_name': 'Event Starting Number', 'verbose_name_plural': 'Event Starting Numbers'},
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='start_date',
            new_name='start_date_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='competitions',
        ),
        migrations.AddField(
            model_name='competition',
            name='event',
            field=models.ForeignKey(default='33f71fec1c78446dab19d0888d1fa7e4', on_delete=django.db.models.deletion.CASCADE, to='events.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competitionstart',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starts', to='events.competition'),
        ),
        migrations.AlterField(
            model_name='competitionstart',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starts', to='events.participant'),
        ),
    ]
