# Generated by Django 5.1.3 on 2024-11-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_competition_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitionstart',
            options={'ordering': ['starting_order'], 'verbose_name': 'Competition Start', 'verbose_name_plural': 'Competition Starts'},
        ),
        migrations.RemoveField(
            model_name='competitionstart',
            name='is_elimination',
        ),
        migrations.AddField(
            model_name='competitionstart',
            name='is_eliminated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='competition',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competitionstart',
            name='completion_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competitionstart',
            name='elimination_type',
            field=models.CharField(blank=True, choices=[('SECOND_REFUSAL', 'Second Refusal'), ('FALLING_OFF', 'Falling Off'), ('FALSTART', 'Falstart'), ('EXCEEDING_TIME_TWICE', 'Exceeding Time Twice'), ('HAND_OFF_REINS', 'Hand Off Reins'), ('HITTING_GROUND', 'Hitting Ground'), ('CONSTANT_TROTTING', 'Constant Trotting'), ('WRONG_OBSTACLE', 'Wrong Obstacle'), ('DANGEROUS_BEHAVIOUR', 'Dangerous Behaviour'), ('DISREGARDING_JUDGES', 'Disregarding Judges'), ('UNAUTHORIZED_JUMP', 'Unauthorized Jump'), ('LEAVING_ARENA', 'Leaving Arena'), ('FAILURE_TO_ARRIVE', 'Failure To Arrive'), ('OTHER', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='competitionstart',
            name='has_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='competitionstart',
            name='has_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='competitionstart',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competitionstart',
            name='penalty_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='competitionstart',
            name='starting_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, to='events.participant'),
        ),
    ]
