# Generated by Django 5.1.3 on 2024-11-13 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_competitionstart_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitionpenalty',
            options={'ordering': ['fence', 'type'], 'verbose_name': 'Competition Penalty', 'verbose_name_plural': 'Competition Penalties'},
        ),
        migrations.AlterModelOptions(
            name='typestranslation',
            options={'ordering': ['translation_key', 'language'], 'verbose_name': 'Types Translation', 'verbose_name_plural': 'Types Translations'},
        ),
    ]
