# Generated by Django 5.1.3 on 2025-06-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_competitionpenalty_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionstart',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competitionstart',
            name='pause_start_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competitionstart',
            name='total_pause_time',
            field=models.IntegerField(default=0),
        ),
    ]
